// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9b521jgQcEfSN8moZ_Oeu4VXAGldG8sU',
    appId: '1:529587095161:web:7f020aa300ba907e1036a8',
    messagingSenderId: '529587095161',
    projectId: 'fir-proyecto-f2d0e',
    authDomain: 'fir-proyecto-f2d0e.firebaseapp.com',
    storageBucket: 'fir-proyecto-f2d0e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv9pS8G3-1Dib0xMavhDuCdMZOjACjTto',
    appId: '1:529587095161:android:c6fe6434f29688011036a8',
    messagingSenderId: '529587095161',
    projectId: 'fir-proyecto-f2d0e',
    storageBucket: 'fir-proyecto-f2d0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB47O30hm8jZ2d3DyEgyZBUXhZG6O2n8U',
    appId: '1:529587095161:ios:03f126d7a3e540481036a8',
    messagingSenderId: '529587095161',
    projectId: 'fir-proyecto-f2d0e',
    storageBucket: 'fir-proyecto-f2d0e.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
